openapi: 3.0.0
info:
  title: Notehub API
  version: 1.0.0
  description: API documentation for notehub

servers:
  - url: https://notehub-vr3x.onrender.com/
    description: Local development server

paths:
  /api/v1/auth/register:
    $ref: "./paths/auth.yaml#/register"
  /api/v1/auth/login:
    $ref: "./paths/auth.yaml#/login"
  /api/v1/auth/logout:
    $ref: "./paths/auth.yaml#/logout"
  /api/v1/auth/me:
    $ref: "./paths/auth.yaml#/me"

  /api/v1/note:
    $ref: "./paths/note.yaml#/note"
  /api/v1/note/{id}:
    $ref: "./paths/note.yaml#/noteById"

components:
  $ref: "./components.yaml"
